# Assignment 01 - Source Distribution on an Airfoil 

Potential flow can represent a flow around ANY shape, not just a cylinder like we saw in Lesson03 

Objective is to build the flow around a NACA0012 airfoil, using a set of sources. 

For non-lifting bodies, you can use a *source* distribution on the body surface, superimposed with a free stream. 

**Before the assignment**
With alpha = $0^o$, 
* Where is the point of maximum pressure?
    * we saw that the point of maximum pressure was along the center line in the front of the object, basically the point of impact with an outward normal parallel the the free stream 
* What do we call that point?
    * we call that point the stagnation point. 
* Will the airfoil generate any lift?
    * sure? 
    
Loading the appropriate libraries and the data from the *resources* folder from the *lessons* folder in the **Aeropython** folder on github 


In [1]:
import numpy 
import math
from matplotlib import pyplot

In [9]:
pwd

'/home/jennakosborn/mae6226/workspace'

In [137]:
x_sources=numpy.loadtxt('../AeroPython/lessons/resources/NACA0012_x.txt')
y_sources=numpy.loadtxt('../AeroPython/lessons/resources/NACA0012_y.txt')
sigmas = numpy.loadtxt('../AeroPython/lessons/resources/NACA0012_sigma.txt')
numpy.size(sigmas)

100

We want to calculate 51 meshpoints in each direction and a domain of [-1,2] by [-0.5, 0.5], we will calculate the velocity components due to a set of *sources* plus a freestream with velocity of 1. We are also going to compute the pressure coefficient. 

Following the convention of the class for defining the variables 



In [52]:
N = 51   # number of points

# creating the mesh 
x_start, x_end = -1.0, 2.0 
y_start, y_end = -0.5, 0.5 
x = numpy.linspace(x_start, x_end, N)
y = numpy.linspace(y_start, y_end, N)  

X, Y = numpy.meshgrid(x,y)


In [145]:
U_tot = numpy.zeros((100,51,51),dtype='float')
V_tot = numpy.zeros((100,51,51),dtype ='float')

# calculating all the individual velocity fields 
for i in range(100):
    U_tot[i,:,:] = sigmas[i]/(2*math.pi) * (X-x_sources[i])/((X-x_sources[i])**2 + (Y-y_sources[i])**2)
    V_tot[i,:,:] = sigmas[i]/(2*math.pi) * (Y-y_sources[i])/((X-x_sources[i])**2 + (Y-y_sources[i])**2)
    

# now summing them individually 
u = numpy.sum(U_tot,axis =0)
v = numpy.sum(V_tot,axis =0)

In [149]:
# plot the streamlines
size = 10
pyplot.figure(figsize=(size, (y_end-y_start)/(x_end-x_start)*size))
pyplot.xlabel('x', fontsize=16)
pyplot.ylabel('y', fontsize=16)
pyplot.xlim(x_start, x_end)
pyplot.ylim(y_start, y_end)


print('something')

something


In [136]:
c= numpy.zeros((3,2,3),dtype ='float')
l = range(3)
a = numpy.array([(1,2,3),(4,5,6)])
b = numpy.array([2,4,6])
for i in l:
    c[i,:,:]= b[i]*a
    print(c)
    print( b[i])



[[[  2.   4.   6.]
  [  8.  10.  12.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]]]
2
[[[  2.   4.   6.]
  [  8.  10.  12.]]

 [[  4.   8.  12.]
  [ 16.  20.  24.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]]]
4
[[[  2.   4.   6.]
  [  8.  10.  12.]]

 [[  4.   8.  12.]
  [ 16.  20.  24.]]

 [[  6.  12.  18.]
  [ 24.  30.  36.]]]
6
