# Lesson 00- Python Crash Course

Lets get started with some notes on Python! Woot! 

## Libraries
The libraries are pre-defined functions that are written for python users. 
Have to import them when we need them. 

**Numpy** is the library of useful of array operations (like Matlab) 
**Matplotlib** is the libary of 2D plotting functions 

Lets import! 

In [2]:
# COMMENTS 
import numpy 
from matplotlib import pyplot  # we are importing a MODULE from a big library of matplotlib

From **NumPy** we want to create a equally space vector, we will use the function **linspace()**, it takes imputs of [beginning, end, number of points]

If the number of points is not designated, it defaults to 50. YOU HAVE TO USE the form below, or it will throw an error

In [3]:
myarray = numpy.linspace(0,5,10)
print(myarray)

[ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]


# Variables 

Sometimes we want to assign a variable to a value, like such... 


In [4]:
a = 5  #integer 
b = 'five' #string 
c = 5.0 #float!

Let's try to ask to see if python knows the difference of these variables 

In [5]:
type(a)

int

In [6]:
type(b)


str

In [7]:
type(c)

float

Floasts and integers math produce the correct value to machine precision.

In [8]:
14/a

2.8

In [9]:
14/c


2.8

Both produce a floating point number 

## Whitespace in Python

Python uses indents and whitespace to group statements. 

In C it would look something like this....

for (i = 0, i < 5, i++){
    printf("Hi! \n"); 
}

Lets take a look at what the python command looks like... 


In [10]:
for i in range(5): 
    print("HI! \n") #\n adds an extra space between HI!'s

HI! 

HI! 

HI! 

HI! 

HI! 



**range()** function - nifty built-in function of python that gives you a list from a arithmetic progression. 

What does a nested loops look like? 

In [11]:
for i in range(3):
    for j in range(3):
        print(i,j)
        print("THIS statement is in BOTH")
        
    print("This statement is contained in the i-loop, NOT the j-loop")
    #which is why it appears 3 times instead of 9 times
        

0 0
THIS statement is in BOTH
0 1
THIS statement is in BOTH
0 2
THIS statement is in BOTH
This statement is contained in the i-loop, NOT the j-loop
1 0
THIS statement is in BOTH
1 1
THIS statement is in BOTH
1 2
THIS statement is in BOTH
This statement is contained in the i-loop, NOT the j-loop
2 0
THIS statement is in BOTH
2 1
THIS statement is in BOTH
2 2
THIS statement is in BOTH
This statement is contained in the i-loop, NOT the j-loop


# Slicing arrays 

In numpy we can look at portions of arrays in the same way in matlab...

In [12]:
myvals = numpy.array([1,2,3,4,5])
myvals


array([1, 2, 3, 4, 5])

**PYTHON IS ZERO-BASED INDEX** 

In [13]:
myvals[0], myvals[4]

(1, 5)

If you want to take a certain part of an array, index it like so...

In [14]:
myvals[0:3]

array([1, 2, 3])

 _*it is important to note that python is inclusive on the front-end, not the back end. Hence, myvals[3] is not included in the subscripted portion._
 
 ## Assigning array variables 
 
 Let's start by creating an array. 

In [17]:
a = numpy.linspace(1,5,5)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [18]:
b=a
b


array([ 1.,  2.,  3.,  4.,  5.])

When you change a value in _a_ it will also be changed in _b_

In [19]:
a[2]=27
a


array([  1.,   2.,  27.,   4.,   5.])

In [20]:
b

array([  1.,   2.,  27.,   4.,   5.])

Let's try something else so that we can do something that actually makes the copy not change when the first is. 

In [21]:
c = a.copy()
c


array([  1.,   2.,  27.,   4.,   5.])

In [23]:
a[2]=3
a


array([ 1.,  2.,  3.,  4.,  5.])

In [24]:
c


array([  1.,   2.,  27.,   4.,   5.])

Perfect! 

## If, elseif, and else statements 

An if statement is a good way to test how to 